name: '🚀 New feature'
description: New feature that will improve EpiTrello
labels: ['pending triage']
projects: ['epi-trello/1']
type: feature
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is and what problem it solves.
      placeholder: Feature description
    validations:
      required: true
